/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/sysinit.o
ringsce.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/system.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/objpas.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/sysutils.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/classes.o
cli.o
openai.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/baseunix.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/unix.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/errors.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/sysconst.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/unixtype.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/sysctl.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/initc.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/unixutil.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/ctypes.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/types.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/typinfo.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/rtlconsts.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/sortbase.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/math.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-web/fphttpclient.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/openssl/opensslsockets.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-json/fpjson.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-json/jsonparser.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-base/base64.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-process/process.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-net/ssockets.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-web/httpdefs.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-base/uriparser.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-net/sslsockets.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl-extra/sockets.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-net/fpsockets.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl-objpas/tuples.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/termio.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl-objpas/nullable.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-net/resolve.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-net/netdb.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-web/httpprotocol.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl-objpas/dateutils.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl-objpas/system.timespan.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl-objpas/strutils.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-net/sslbase.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/openssl/openssl.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/openssl/fpopenssl.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/dynlibs.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl/dl.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl-objpas/variants.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-base/contnrs.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/rtl-objpas/varutils.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-json/jsonscanner.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-json/jsonreader.o
/usr/local/lib/fpc/3.3.1/units/aarch64-darwin/fcl-process/pipes.o
