project(ringsCE)
cmake_minimum_required(VERSION 3.24)
#find_package(SDL2 REQUIRED CONFIG)
#find_package(SDL2_image 2 REQUIRED)
#find_package(SDL2_net 2 REQUIRED)
#find_package(SDL2_ttf 2 REQUIRED)
#find_package(SDL2_mixer 2 REQUIRED)

include(CheckLibraryExists)
#include(${CMAKE_MODULE_PATH}/utils.cmake)
